name: rnaseq_preprocess
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bioconductor-rtracklayer
  - bioconductor-tximport
  - fastqc
  - multiqc
  - r-jsonlite
  - salmon=1.10.3
  - seqtk
